Website/Models/Characters.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Code;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Website.Models
{

    public class Characters
    {
        public int CharacterList { get; set; }
        public List<SelectListItem> SelectableCharacters { get; set; }
    }
}

Website/Models/CheatSheet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Website.Models
{

    public class CheatSheet
    {
        [Display(Name = "First name: (from Model)")]
        public string FirstName { get; set; }

        [Display(Name = "Last name: (from Model)")]
        public string LastName { get; set; } = "Aslett";

        [Display(Name = "Phone number:")]
        [Phone]
        public string PhoneNumber { get; set; }

        [Display(Name = "Mail address:")]
        [EmailAddress]
        public string MailAddress { get; set; }

        [Display(Name = "Password:")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "DOB:")]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }

        [Display(Name = "Is active:")]
        public bool IsActive { get; set; }

        public string TextArea { get; set; }

        [MinLength(2)]
        [MaxLength(25)]
        public string TextAreaLength { get; set; }

        public string Gender { get; set; }

        public List<SelectListItem> Genders { get; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "1", Text = "Male" },
            new SelectListItem { Value = "2", Text = "Female" },
        };

        public List<Country> Countries { get; set; }
        public string SelectedCountry { get; set; }

        public enum DayOfWeek
        {
            Sunday = 0,
            Monday = 1,
            Tuesday = 2,
            Wednesday = 3,
            Thursday = 4,
            Friday = 5,
            Saturday = 6
        }

        public string SelectedDay { get; set; }

        public List<Movie> Movies { get; set; }
    }

    public class Country 
    {
        public string Abbreviation { get; }

        public string Name { get; }

        public string NameAndAbbreviation => $"{Name} - {Abbreviation}";

        public Country(string abbreviation, string name)
        {
            Abbreviation = abbreviation;
            Name = name;
        } 
    }


    public class Movie
    {
        public int Id { get; set; }

        public string Title { get; set; }

    }

    public class GetterAndSetterLearning
    {
        //field - fields tend to be private/protected (scoped to Class) - with fields you have no control over who can get and set the value
        public bool MyField;

        //property - has a getter/setter/both. Getter = whether property can be read, Setter = where property value can be changed. Properties allow you to have more control over getting/setting

        //can read and write
        public bool MyProperty1 { get; set; }

        //can only read

        public bool MyProperty2 { get; }

        private bool _myBackingField;

        //property where we have specified what the getters and setters do
        public bool MyProperty3 
        { 
            get 
            {
                return _myBackingField;
            }
            set
            {
                _myBackingField = value;
            }
        }
    }

}

Website/Controllers/CheatSheetController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Website.Models;

namespace Website.Controllers
{
    public class CheatSheetController : Controller
    {
        public IActionResult Index()
        {
            //you must new up an instance of the Model in the Controller, or the View won't know anything about the properties in the Model
            var CheatSheetModel = new CheatSheet();
            CheatSheetModel.Countries = new List<Country>()
            {            
                new Country("USA", "United States of America"),
                new Country("GB", "United Kingdom"),
                new Country("GRY", "Germany"),  
            };
            CheatSheetModel.Movies = new List<Movie>()
            {
        new Movie() { Id = 1, Title = "The Godfather" },
        new Movie() { Id = 2, Title = "Forrest Gump" },
        new Movie() { Id = 3, Title = "Fight Club" },
            };
            return View(CheatSheetModel);
        }
    }
}

Website/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Http(int statusCode)
        {
            // Log error, e.g. to a database. You can use the HttpContext.Request object to access important information like the requested URL 

            if (statusCode == 404)
            {
                return View("Error404"); //return 404 specific View
            }
            return View("ErrorGeneric"); //return generic View
        }
    }
}

Website/Controllers/HomeController.cs
using Code;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Website.Models;

namespace Website.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            //get characters from Dictionary and store as List<SelectListItem>
            var selectableCharacters = SummerHeightsHighService.Characters
                    .Select(kvp => new SelectListItem(kvp.Value.Name, kvp.Key))
                    .ToList();

            //new up Characters Model, as this ViewDataDictionary instance requires a Model item of type 'Website.Models.Characters'
            var characterListModel = new Characters();

            //sets our selectableCharacters variable to SelectableCharacters in Model
            characterListModel.SelectableCharacters = selectableCharacters;

            return View(characterListModel);
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

Website/Controllers/JaMieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Controllers
{
    public class JaMieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Website/Controllers/JonahController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Controllers
{
    public class JonahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Website/Controllers/MrGController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Controllers
{
    public class MrGController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Website/Views/CheatSheet/Index.cshtml
@model CheatSheet
@{
    ViewData["Title"] = "Cheat Sheet Page";
}

<div class="text-center">
    <h1 class="display-4">Cheat Sheet</h1>

    @*FORM TAGS*@
    @*form tag should be around any form elements that you want to submit back to the server, including inputs, textareas etc*@
<form method="post" asp-controller="CheatSheet" asp-action="Index">
    <h3>LABELS</h3>
    <p>If you give the label's <i>for</i> attribute the same value as the control's ID, it'll link them. This will make the label area clickable as well.</p>
    <div>
        <label for="FirstName">First name:</label>
        <input asp-for="FirstName" />
    </div>
    <p>
        To connect the label to a Model use <i>asp-for</i>. Note that you no longer have to specify the text of the label as it'll be pulled from the Model, and the
        HTML for attribute will be automatically generated.
    </p>
    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" />
    </div>
    <br />
    <h3>INPUTS</h3>
    <p>The Input Tag Helper only has the <i>asp-for</i> attribute. This allows you to bind the Input control to a property on the Model. In this case the input is populated with 'Aslett' because this value is set in the Model.</p>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" />
    </div>
    <br />

    <h5>Using Data Annotations to denote type</h5>
    <div>
        <label asp-for="MailAddress"></label>
        <input asp-for="MailAddress" />
    </div>
    <div>
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" />
    </div>
    <div>
        <label asp-for="Password"></label>
        <input asp-for="Password" />
    </div>
    <div>
        <label asp-for="DateOfBirth"></label>
        <input asp-for="DateOfBirth" />
    </div>
    <div>
        <label asp-for="IsActive"></label>
        <input asp-for="IsActive" />
    </div>
    <br />
    <h3>TEXTAREA</h3>
    <p>The TextArea Tag Helper uses the <i>asp-for.</i> If no size is specified then it will be decided by the browser:</p>

    <textarea asp-for="TextArea"></textarea>

    <p>Or you can specify a size in the markup:</p>

    <textarea asp-for="TextArea" style="height: 40px; width: 200px;"></textarea>

    <p>You can also specify min and max lengths in the Model. This has a min of 2 and a max of 25:</p>

    <textarea asp-for="TextAreaLength"></textarea>

    <p>Min lengths aren't part of the HTML specification, so there's no relevant attribute for the browser to work with. However, it's still relevant to specify on the Model, especially if you use Model Validation. The rendered result will show you that only max length is directly supported by the HTML specification - the min length is only rendered as a data attribute, to be used by client-side Model Validation.</p>

    <h3>SELECT</h3>
    <p>The Select Tag Helper has the <i>asp-for</i> attribute, which allows you to bind its selected value to a specific property on the Model. The <i>asp-items</i> tag allows you to provide a data source for the SELECT element. In this example the options are held in the Model:</p>

    <label asp-for="Gender" class="control-lable"></label>
    <select asp-for="Gender" asp-items="Model.Genders" class="custom-select">
        <option value="">Choose Gender</option>
    </select>
    <br />
    <br />
    <p>In this example the options are held in the Controller and passed through to the View:</p>

    <select asp-items="@(new SelectList(Model.Countries.Select(x => x.Name)))" asp-for="SelectedCountry"></select>
    <br />
    <br />
    <p>In the above examples no values are provided for the option tags, meaning that the text of the option will be used as the value when submitting. That's because we are generating the options from a simple list of strings, however in most situations you are more likely to generate lists based on a combination of keys and values, eg: the values may come from a database, where they use a number as ID's.</p>

    <select asp-items="@(new SelectList(Model.Countries, "Abbreviation", "Name"))" asp-for="SelectedCountry"></select>

    <select asp-items="@(new SelectList(Model.Countries, "Abbreviation", "NameAndAbbreviation"))" asp-for="SelectedCountry"></select>

    <select asp-items="@Model.Countries.Select(x => new SelectListItem(x.Name, x.Abbreviation))" asp-for="SelectedCountry"></select>
    <br />
    <br />
    <p>Another very common usage is with enumerations (enums), for example the DayOfWeek enumeration. This will assign numbers to the values, starting at 0:</p>

    <select asp-items="@(Html.GetEnumSelectList<DayOfWeek>())" asp-for="SelectedDay"></select>
    <br />
    <br />
    <h3>ANCHOR TAG</h3>

    <p>The Anchor Tag Helper can help you link to Actions on your Controller. The most commonly used attributes are <i>controller</i> and <i>action</i>, allowing you to speficy which Controller and Action to use.</p>

    <a asp-controller="Home" asp-action="Index">Link to Index Action on Home controller</a>
    <br />
    <br />

    <a asp-controller="Jonah" asp-action="Index">Link to Index Action on Jonah Controller</a>
    <br />
    <br />

    <p>There is also an <i>asp-route-{value}</i> attribute. Any value added in place of {value} is considered a route parameter. If a default route is not found, this value will be used to generate the URL as a request parameter and value:</p>

    <a asp-controller="CheatSheet" asp-action="Index" asp-route-id="12">Link to Jonah/Index/12</a>
    <br />
    <br />
    <p>In this example we generate a new link for each of the movies in the list and generate a new URL for each of them:</p>
    <ul>
        @foreach (var movie in Model.Movies)
        {
            <li>
                <a asp-controller="CheatSheet" asp-action="Index" asp-route-id="@movie.Id">@movie.Title</a>
            </li>
        }
    </ul>

    <p>If you want to refer to a specific part of the page, use the <i>asp-fragment</i> attribute:</p>

    <a asp-controller="CheatSheet" asp-action="Index" asp-fragment="test">Link using asp-fragment</a>

    <p>This enables you to link to an element on the same page that you're currently on, eg: for jumping to certain sections</p>

    <p>If you need to specify the host name in the link, eg: google.com then use <i>asp-host</i>. Usually not necessary because the value can be fetched from the website automatically:</p>

    <a asp-controller="CheatSheet" asp-action="Index" asp-host="google.com">Link using asp-host</a>

    <p>If you want to force a protocol other than the one used, eg: from http to https then use <i>asp-protocol</i>:</p>

    <a asp-controller="CheatSheet" asp-action="Index" asp-host="google.com" asp-protocol="https">Movie list</a>
    <br />
    <br />
    <h3>SCRIPT TAG</h3>

    <p>To import script files. Best practice is to use CDN with a local fallback. The Script Tag Helper can help with this. The Script Tag helper requires a value for the <i>fallback-src</i> attribute, as an alternative to the regular <i>src</i> attribute:</p>

    @Html.Raw("&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js&quot; asp-fallback-src=&quot;~&#47;Content&#47;jquery.min.js&quot;&gt;&lt;&#47;script&gt")

    <br />
    <br />
    <p>In this case, jQuery will be loaded from cdnjs first, but if that fails a local version will be requested instead. However, detecting that the CDN has failed to deliver the required JS file can be difficult, but it can be achieved with the <i>fallback-test</i> attribute:</p>

    @Html.Raw("&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js&quot; asp-fallback-src=&quot;~&#47;Content&#47;jquery.min.js&quot; asp-fallback-test=&quot;window.jQuery&quot;&gt&lt;&#47;script&gt")
    <br />
    <br />
    <p>This will ensure that if the CDN version didn't load then the fallback will be used.</p>
    <br />
    <br />
    <h3>LINK TAG</h3>

    <p>To import CSS files. Uses the <i>href</i> to dictate which file to use, and <i>fallback-href</i>, which will be the path used if the CDN version fails:</p>

    @Html.Raw("&lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js&quot; asp-fallback-href=&quot;~/Content/bootstrap.min.css&quot; /&gt;")

    <p>In this case, the CSS for Bootstrap will be loaded from cdnjs, and it that fails a local version will be requested. However, detecting that the CDN has failed to deliver the required CSS file can be difficult, but the Link Tag Helper can help you with this.</p>

    <p>Loading CSS from a CDN may fail silently, meaning that your page will look wrong because of the missing CSS. We can use the one or several attributes for testing whether the desired CSS was loaded properly. Further reading <a href="https://asp.mvc-tutorial.com/tag-helpers/the-link-tag-helper/">here</a></p>

</form>
</div>

Website/Views/Home/Index.cshtml
@model Characters
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Summer Heights High</h1>
    <p>Character Lookup System</p>
    <p style="color:red;"><b><i>User should be select a name and click button, then character details should display below. Instead of the input box, could we populate a dropdown from DisplayListOfCharacters?</i></b></p>
    <label for="CharacterList">Please select a character:</label>
    <select asp-for="CharacterList" asp-items="@Model.SelectableCharacters" class="all-width">
        <option value="">Choose</option>
    </select>
    <button>Let's go!</button>
</div>

Website/Views/JaMie/Index.cshtml
@{
    ViewData["Title"] = "Ja'Mie Page";
}

<div class="text-center">
    <h1 class="display-4">Ja'Mie</h1>
    <p>[Display character info here]</p>
    <p style="color:red;"><b><i>Can we use ReturnCharacter in SummerHeightsHighService.cs?</i></b></p>
</div>

Website/Views/Jonah/Index.cshtml
@{
    ViewData["Title"] = "Jonah Page";
}

<div class="text-center">
    <h1 class="display-4">Jonah</h1>
    <p>[Display character info here]</p>
    <p style="color:red;"><b><i>Can we use ReturnCharacter in SummerHeightsHighService.cs?</i></b></p>
</div>

Website/Views/MrG/Index.cshtml
@{
    ViewData["Title"] = "Mr G Page";
}

<div class="text-center">
    <h1 class="display-4">Mr G</h1>
    <p>[Display character info here]</p>
    <p style="color:red;"><b><i>Can we use ReturnCharacter in SummerHeightsHighService.cs?</i></b></p>
</div>

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JaMie" asp-action="Index">Ja'Mie</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jonah" asp-action="Index">Jonah</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="MrG" asp-action="Index">Mr G</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>